version: "3.9"
services:
  todo-database:
    image: postgres:15.3-alpine3.18
    environment:
      - POSTGRES_PASSWORD=pswd
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.80.0
    volumes:
      - ./otel-config.yaml:/etc/otel/config.yaml
    command: --config /etc/otel/config.yaml
    environment:
      - JAEGER_ENDPOINT=jaeger:4317
    ports:
      - "13133:13133" # health_check extension
      - "55679:55679" # zpages extension
      - "4318:4318"   # OTLP HTTP receiver
      - "8889:8889"   # Prometheus metrics exporter (scrape endpoint)
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.46.0
    ports:
      - "16686:16686" # Jaeger Web UI
