receivers:
  otlp:
    protocols:
      http:

processors:
  batch:

exporters:
  otlp:
    endpoint: "${JAEGER_ENDPOINT}"
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"

extensions:
  health_check:
  zpages:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
